<a href="https://colab.research.google.com/github/brus2099/daa_2021_1/blob/master/Tarea4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
def ejemplo4(n):
  count = 0
  i = n
  #print(f'count: {count}   i: {i}')
  while i >=1 :
    count += 1
    i = i//2
    #print(f'count: {count}   i: {i}')
  basura = 3 + 2
  return count

def __main__():
  for i in range(100):
    print(f'For 10**{i} = {ejemplo4(10**i)}')

__main__()

For 10**0 = 1
For 10**1 = 4
For 10**2 = 7
For 10**3 = 10
For 10**4 = 14
For 10**5 = 17
For 10**6 = 20
For 10**7 = 24
For 10**8 = 27
For 10**9 = 30
For 10**10 = 34
For 10**11 = 37
For 10**12 = 40
For 10**13 = 44
For 10**14 = 47
For 10**15 = 50
For 10**16 = 54
For 10**17 = 57
For 10**18 = 60
For 10**19 = 64
For 10**20 = 67
For 10**21 = 70
For 10**22 = 74
For 10**23 = 77
For 10**24 = 80
For 10**25 = 84
For 10**26 = 87
For 10**27 = 90
For 10**28 = 94
For 10**29 = 97
For 10**30 = 100
For 10**31 = 103
For 10**32 = 107
For 10**33 = 110
For 10**34 = 113
For 10**35 = 117
For 10**36 = 120
For 10**37 = 123
For 10**38 = 127
For 10**39 = 130
For 10**40 = 133
For 10**41 = 137
For 10**42 = 140
For 10**43 = 143
For 10**44 = 147
For 10**45 = 150
For 10**46 = 153
For 10**47 = 157
For 10**48 = 160
For 10**49 = 163
For 10**50 = 167
For 10**51 = 170
For 10**52 = 173
For 10**53 = 177
For 10**54 = 180
For 10**55 = 183
For 10**56 = 187
For 10**57 = 190
For 10**58 = 193
For 10**59 = 196
For 10**60 = 200
For 10**61 = 203
For 10**62 = 206
For 10**63 = 210
For 10**64 = 213
For 10**65 = 216
For 10**66 = 220
For 10**67 = 223
For 10**68 = 226
For 10**69 = 230
For 10**70 = 233
For 10**71 = 236
For 10**72 = 240
For 10**73 = 243
For 10**74 = 246
For 10**75 = 250
For 10**76 = 253
For 10**77 = 256
For 10**78 = 260
For 10**79 = 263
For 10**80 = 266
For 10**81 = 270
For 10**82 = 273
For 10**83 = 276
For 10**84 = 280
For 10**85 = 283
For 10**86 = 286
For 10**87 = 290
For 10**88 = 293
For 10**89 = 296
For 10**90 = 299
For 10**91 = 303
For 10**92 = 306
For 10**93 = 309
For 10**94 = 313
For 10**95 = 316
For 10**96 = 319
For 10**97 = 323
For 10**98 = 326
For 10**99 = 329